core/urls.py
from django.urls import path, include
from core import views
app_name = 'core'

urlpatterns = [
    path('',views.HomeView.as_view(), name = 'home'),
    path('product/<slug>/', views.ItemDetails.as_view(),name='product'),
    path('add_to_cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary/',views.OrderSummary.as_view(),name='order-summary'),
    path('remove_single_item/<slug>/',views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/',views.CheckoutView.as_view(),name='checkout'),
    path('payment/<payment_info>/',views.PaymentView.as_view(), name='payment'),

]

ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('',include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
# Create your models here.

CATEGORY_CHOICES = (
        ('S','Shirt'),
        ('SW','Sports Wear'),
        ('OW','Out Wear'),
)

LABEL_CHOICES = (
        ('P','primary'),
        ('S','success'),
        ('D','danger'),
)

PAYMENT_METHOD = (
    ('S','Stripe'),
    ('P',"PayPal"),
)


class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_price = models.FloatField()
    item_discounted_price = models.FloatField(null=True,blank=True)
    item_description = models.TextField()
    item_category = models.CharField(choices=CATEGORY_CHOICES, default='S', max_length=2)
    item_label = models.CharField(choices=LABEL_CHOICES, default='P', max_length=1)
    item_discount = models.PositiveIntegerField(null=True,blank=True)
    item_image = models.CharField(max_length=500,default='http://leeford.in/wp-content/uploads/2017/09/image-not-found.jpg')
    slug = models.SlugField(default='test-product')
    

    class Meta:
        db_table = 'Item'
    
    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse('core:product', kwargs={
                    'slug':self.slug
        })
    
    def get_add_to_cart_url(self):
           return reverse('core:add-to-cart', kwargs={
                    'slug':self.slug
        })
    
    def get_remove_from_cart_url(self):
        return reverse('core:remove-from-cart', kwargs={
                    'slug':self.slug
        })

    def get_item_price(self):
        if self.item_discounted_price:
            return self.item_discounted_price
        else:
            return self.item_price


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, blank=True, null=True)
    order_item = models.ForeignKey(Item, on_delete = models.CASCADE)
    item_quantity = models.PositiveIntegerField(default=1)
    is_ordered = models.BooleanField(default=False)

    class Meta:
        db_table = 'Order Item'

    def __str__(self):
        return str(self.item_quantity) + " " + self.order_item.item_name

    def get_total_item_price(self):
        return  self.item_quantity * self.order_item.get_item_price()

    def get_total_savings(self):
        if self.order_item.item_discounted_price:
            return (self.order_item.item_price - self.order_item.item_discounted_price)*self.item_quantity
        else:
            return 0

class BillingInformation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    street = models.CharField(max_length=300)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=6)
    state = models.CharField(max_length=100)
    landmark = models.CharField(max_length=500)
    shipping_same_as_billing = models.BooleanField(default=False)
    save_info = models.BooleanField(default=False)
    payment_info = models.CharField(choices=PAYMENT_METHOD,max_length=1)

    def __str__(self):
        return self.street+ " " + self.city+ " " + self.state


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,blank=True, null=True)
    amount = models.FloatField(default=0)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    order_items = models.ManyToManyField(OrderItem)
    date_of_order = models.DateTimeField()
    is_ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(BillingInformation,on_delete=models.PROTECT,blank=True,null=True)
    payment = models.ForeignKey(Payment,on_delete=models.SET_NULL,null=True)

    class Meta:
        db_table = 'Order'
    
    def __str__(self):
        return self.user.username

    def get_cart_total(self):
        price = 0
        for i in self.order_items.all():
            price += i.get_total_item_price()
        return price

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/js/mdb.min.js"></script>

</head>

<body>

    <!-- Navigation bar -->

    <nav class="navbar navbar-inverse navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">MyeComm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href='/order-summary/'>My Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="">Hey!! {{request.user.username}}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/accounts/logout">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/signup">Register</a>
                </li>
                {% endif %}
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li> -->

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <br>


    <div class="container">

        {% block content  %}
        {% endblock content %}

        {% block extra_body %}
        {% endblock %}
</body>

</div>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Checkout</h1>

<form action="/payment/stripe/">
    {% csrf_token %}
    {{form|crispy}}
    <a href="/payment/stripe/" class="btn btn-default" href=''>Proceed to checkout..</a>
</form>

{% endblock %}

templates/empty-cart.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <h1>Your cart is empty. Please add items to your cart.</h1>
</div>



{% endblock %}

templates/home.html
{% extends 'base.html' %}


<div class="alert alert-{{ messages.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>



{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ messages.tags }} alert-dismissible" style=" background: coral; width: 100%;"
        role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
</ul>
{% endif %}


<style>
    .card {
        width: 100%;
    }

    img {
        align-self: center;
    }
</style>

{% for item in object_list %}


<div class="container">
    <div class="container card">
        <img src={{item.item_image}} alt="Card image cap" width="400px" height="500px">
        <div class="card-body">
            <a href={{item.get_absolute_url}}>
                <h5 class="card-title">{{item.item_name}}</h5>
            </a>
            <p class="card-text">{{item.item_description}}</p>
            {% if item.item_discounted_price %}

            <a class="btn btn-default"><del>Rs. {{item.item_price}}</del></a>

            <a class="btn btn-primary">Rs. {{item.item_discounted_price}}</a>
            <button type="button" class="btn btn-outline-success">{{item.item_discount}}% Discount !!!</button>

            {% else %}
            <a class="btn btn-primary">Rs. {{item.item_price}}</a>
            {% endif %}


        </div>
    </div>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


</div>

{% endfor %}

{% endblock %}

templates/order-summary.html
{% extends 'base.html' %}

{% block content %}
<style>
    td {
        text-align: center;
        vertical-align: center;
    }
</style>

<h2>
    Order Summary
</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#####</th>
            <th scope="col">Item Name</th>
            <th scope="col">Item Quantity</th>
            <th scope="col">Item Price</th>
            <th scope="col">Total Item Price</th>
        </tr>
    </thead>
    {% if object %}

    {% for order_item in object.order_items.all %}

    <tr>
        <td scope='row'><a href={% url 'core:product' order_item.order_item.slug %}><img
                    src={{order_item.order_item.item_image}} alt="" width="100px" height="100px"></a></td>
        <td><br><br><a href={% url 'core:product' order_item.order_item.slug %}>{{order_item.order_item.item_name}}</a>
        </td>
        <td><br><br> <a href="{% url 'core:remove-single-item-from-cart' order_item.order_item.slug %}">
                <i class="fas fa-minus-circle"></i>

            </a>

            &nbsp;&nbsp;{{order_item.item_quantity}} &nbsp;


            <a href={% url 'core:add-to-cart' order_item.order_item.slug %}>
                <i class="fas fa-plus-circle"></i>
            </a>
        </td>

        <td><br><br>{{order_item.order_item.get_item_price}}</td>
        <td><br><br>{{order_item.get_total_item_price}}
            &nbsp;&nbsp;&nbsp;
            {% if order_item.get_total_savings %}
            <span class="badge badge-pill badge-success">Total Savings : Rs.{{ order_item.get_total_savings}}!!!</span>
            {% endif %}
        </td>
    </tr>
    {% empty %}

    <tr>
        <th colspan='4'>Your cart is empty </th>

    </tr>


    {% endfor %}

    {% else %}

    <div class="jumbotron">
        <h1>Your cart is empty</h1>
    </div>





    {% endif %}




    <tr>
        <th colspan='4'>Cart Total </th>
        <th>Rs.{{object.get_cart_total}}</th>
    </tr>


</table>

<a float='right' class="btn btn-primary float-right" href={% url 'core:checkout' %}>Proceed to
    checkout &nbsp; <i class="fas fa-long-arrow-alt-right"></i></a>
<a href="/" class="btn btn-default"><i class="fas fa-long-arrow-alt-left"></i> &nbsp; Continue shopping...</a>


{% endblock %}

templates/order_placed.html
{% extends 'base.html' %}

{% block content %}






<h1>Yayyy.......</h1>

<h2>Your order has been placed....</h2>





{% endblock %}

templates/payment.html
{% extends 'base.html' %}

{% block extra_head %}
<style>
    #stripeBtnLabel {
        font-family: "Helvetica Neue", Helvetica, sans-serif;
        font-size: 16px;
        font-variant: normal;
        padding: 0;
        margin: 0;
        -webkit-font-smoothing: antialiased;
        font-weight: 500;
        display: block;
    }

    #stripeBtn {
        border: none;
        border-radius: 4px;
        outline: none;
        text-decoration: none;
        color: #fff;
        background: #32325d;
        white-space: nowrap;
        display: inline-block;
        height: 40px;
        line-height: 40px;
        box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
        border-radius: 4px;
        font-size: 15px;
        font-weight: 600;
        letter-spacing: 0.025em;
        text-decoration: none;
        -webkit-transition: all 150ms ease;
        transition: all 150ms ease;
        float: left;
        width: 100%;
    }

    #stripeBtn:hover {
        transform: translateY(-1px);
        box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
        background-color: darkblue;
    }

    #stripe-form {
        padding: 5px 30px;
    }

    #card-errors {
        height: 20px;
        padding: 4px 0;
        color: #fa755a;
    }

    .stripe-form-row {
        width: 80%;
        float: left;
        margin-top: 5px;
        margin-bottom: 5px;
    }

    /**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
    .StripeElement {
        box-sizing: border-box;
        height: 40px;
        padding: 10px 12px;
        border: 1px solid transparent;
        border-radius: 4px;
        background-color: white;
        box-shadow: 0 1px 3px 0 #e6ebf1;
        -webkit-transition: box-shadow 150ms ease;
        transition: box-shadow 150ms ease;
    }

    .StripeElement--focus {
        box-shadow: 0 1px 3px 0 #cfd7df;
    }

    .StripeElement--invalid {
        border-color: #fa755a;
    }

    .StripeElement--webkit-autofill {
        background-color: #fefde5 !important;
    }

    .current-card-form {
        display: none;
    }
</style>
{% endblock extra_head %}



{% block content %}



<body>

    <!-- <script src="https://js.stripe.com/v2/"></script> -->

    <script src="https://js.stripe.com/v3/"></script>

    <form action="." method="post" class="stripe-form" id="stripe-form">
        {% csrf_token %}
        <div class="stripe-form-row" id="creditCard">
            <label for="card-element" id="stripeBtnLabel">
                Credit or debit card
            </label>
            <div id="card-element" class="StripeElement StripeElement--empty">
                <div class="__PrivateStripeElement"
                    style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                    <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5"
                        allowpaymentrequest="true"
                        src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1"
                        title="Secure payment input frame"
                        style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe><input
                        class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false"
                        maxlength="1"
                        style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                </div>
            </div>
        </div>
        <div class="stripe-form-row">
            <button type="submit" id="stripeBtn">Submit Payment</button>
        </div>
        <div class="stripe-form-row">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="save" id="save_card_info">
                <label class="custom-control-label" for="save_card_info">Save for future purchases</label>
            </div>
        </div>
        <div id="card-errors" role="alert"></div>
    </form>
    <!-- <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div> -->




    <!-- <script type="text/javascript" src="/javascripts/jquery-3.1.1.min.js"></script> -->
    <script src="https://js.stripe.com/v3/"></script>
    <!-- <script type="text/javascript" src="/javascripts/jquery-3.1.1.min.js"></script> -->

    <script type="text/javascript" nonce="">
        var stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx');

        // Create an instance of Elements.
        var elements = stripe.elements()

        // Custom styling can be passed to options when creating an Element.
        // (Note that this demo uses a wider set of styles than the guide below.)
        var style = {
            base: {
                color: '#32325d',
                fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                fontSmoothing: 'antialiased',
                fontSize: '16px',
                '::placeholder': {
                    color: '#aab7c4'
                }
            },
            invalid: {
                color: '#fa755a',
                iconColor: '#fa755a'
            }
        };

        // Create an instance of the card Element.
        var card = elements.create('card', { style: style });

        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission.
        var form = document.getElementById('stripe-form');
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            stripe.createToken(card).then(function (result) {
                if (result.error) {
                    // Inform the user if there was an error.
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server.
                    stripeTokenHandler(result.token);
                }
            });
        });

        // Submit the form with the token ID.
        function stripeTokenHandler(token) {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('stripe-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('type', 'hidden');
            // hiddenInput.setAttribute('id', 'stripeToken');

            // hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            // Submit the form
            form.submit();
        }



        // Not in demo.

    </script>
</body>




{% endblock %}

templates/product.html
{% extends 'base.html' %}

{% block content %}

<div align='center'>

    <h1>{{item.item_name}}</h1>
</div>




<div class="container card">
    <img src={{item.item_image}} alt="Card image cap" width="400px" height="500px" center>
    <div class="card-body">
        <button class="btn btn-dark">{{object.get_item_category_display}}</button>
        <button class="btn btn-{{object.get_item_label_display}}">Best seller</button>


        <p class="card-text">{{item.item_description}}</p>
        {% if item.item_discounted_price %}

        <a class="btn btn-primary"><del>Rs. {{item.item_price}}</del></a>

        <a class="btn btn-info">Rs. {{item.item_discounted_price}}</a>
        <button type="button" class="btn btn-outline-success">{{item.item_discount}}% Discount !!!</button>

        {% else %}
        <a class="btn btn-primary">Rs. {{item.item_price}}</a>
        {% endif %}
        <a href={{ object.get_add_to_cart_url }} class="btn btn-success" id='add'>Add to cart</a>
        <a href={{ object.get_remove_from_cart_url }} id='remove' class="btn btn-danger">Remove
            from cart</a>

    </div>


</div>




{% endblock %}